//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddressMapping
    {
        public int CustomerId { get; set; }
        public int AddressId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
